### ISSUE TITLE
[MAC-chrome-1220-회원가입]비밀번호 확인을 맞춘후 비밀번호를 바꾸면 통과되는 버그

### ISSUE THREAD

**Issue by Dwisgolmog** [100-hours-a-week/2-siena-eom-community-fe-1#10]
**버그 설명**
회원가입 페이지에서 비밀번호와 비밀번호 확인을 작성후에 다시 비밀번호를 바꾸면 그대호 회원가입이 진행되는 버그 발생

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지 이동
2. 비밀번호와 비밀번호 확인까지 동일하게 입력
3. 비밀번호의 입력 내용을 변경
4. 비밀번호의 내용으로 그대로 회원가입이 됨

**예상한 동작**
비밀번호를 바꾸어도 비밀번호가 다르다는 helper-text와 함께 회원가입이 진행이 되지 않을것을 예상했음

**스크린샷**
![스크린샷 2024-12-19 오전 11 43 08](https://github.com/user-attachments/assets/fdac600f-4bdd-49a8-b40a-8519cd0a21eb)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: Mac m1
 - Browser: chrome
 - Version: 131.0.6778.140(공식 빌드) (arm64)

**Comment by siyeoneom** [comment]
비밀번호 입력 변경시 비밀번호 확인 칸의 유효성 검사를 실시하도록 했습니당 QA감삼다!!!!
