### ISSUE TITLE
[MAC-chrome-1220-회원가입] 계정 탈취 버그

### ISSUE THREAD

**Issue by Dwisgolmog** [100-hours-a-week/2-siena-eom-community-fe-1#11]
**버그 설명**
아무계정이나 로그인한후에 개발자 도구창에서 세션에서 userId 값을 변경하면 마치 다른사람으로 로그인한 것처럼 보입니다.
이후에 글 작성,수정,삭제 및 회원정보 수정,탈퇴 를 진행할시 로그인한 유저로 적용이 됩니다.
여기서!! 회원정보 수정 페이지로 이동시 회원정보는 세션스토리지 Id값으로 불러와집니다.
콘솔로 세션스토리지 Id값으로 get 요청을 보내면 해당 유저의 모든 정보를 얻을 수 있습니다.
비밀번호가 암호화로 저장되어있지 않아 해당 정보를 기반으로 로그인이 가능합니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 로그인 페이지에서 로그인을 한다.
2. 개발자 도구창에서 application 탭 세션 스토리지에서 userId값을 변경한다.
3. 회원정보 수정 페이지 들어간다.
4. 콘솔창에 다음과 같은 코드를 입력한다. (끝에 파라미터 값으로 다른 유저의 값을 가져올 수 있음)
```
fetch('http://3.39.237.226:3001/users/1', {
    method: 'GET',
    credentials: 'include',
})
    .then(response => {
        if (!response.ok) {
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        return response.json();
    })
    .then(data => {
        console.log(data);
    })
    .catch(error => { 
        console.error('Error:', error);
    });
```
5.콘솔창에 나와있는 회원정보를 토대로 로그인 한다.

**예상한 동작**
세션 스토리지에 있는 id값으로 회원정보를 못가져올것을 예상했음
회원정보를 가져왔을때 비밀번호가 암호화가 되어있을것이라 예상했음

**시연 영상**
https://github.com/user-attachments/assets/1c8509dd-3505-4ddb-b9fe-2a36434575b8

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: Mac m1
 - Browser: chrome
 - Version: 131.0.6778.140(공식 빌드) (arm64)

추가적인 내용
추가로 확인해보니 세션 스토리지의 값을 변경하지 않고, 그냥 로그인한 상태로 요청 보내면 모든 다른 유저 정보를 알 수가 있네요!

**Comment by siyeoneom** [comment]
비밀번호 암호화 (bcrypt) 추가 및 userId를 백엔드 서버측에서 관리하게 하여 브라우저에서 조작할 수 없도록 수정하였습니다.
수정은 완료하였으나 아직 메인 브랜치로 머지하지 않았음 (QA용 배포서버에 업로드는 모든 이슈 내용 close 이후 업데이트 예정)
