### ISSUE TITLE
 [MAC-Chrome-1511-게시글 목록] 게시글 목록 정렬 이슈

### ISSUE THREAD

**Issue by ghkddlscks19** [100-hours-a-week/2-siena-eom-community-fe-1#13]
**버그 설명**
게시글 목록에서 게시글이 최신순으로 정렬되어 있지 않음

**예상한 동작**
최신 게시글이 최상단에 있을 것으로 예상했음

**스크린샷**
<img width="641" alt="image" src="https://github.com/user-attachments/assets/c556921d-8331-4102-9ee2-a750ab55ab55" />

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: macOS 14.3
 - Browser chrome
 - Version 버전 131.0.6778.205(공식 빌드) (arm64)

**Comment by siyeoneom** [comment]
posts 데이터를 날짜로 정렬하여 최신순으로 나타나도록 수정완료하였습니당 (아직 메인 브랜치로 머지하지 않음, QA용 배포서버에 업로드는 모든 이슈 내용 close 이후 업데이트 예정)
