### ISSUE TITLE
 [MAC-Chrome-1511-게시글 수정] 게시글 수정 시 기존 이미지 파일 명이 안뜸

### ISSUE THREAD

**Issue by ghkddlscks19** [100-hours-a-week/2-siena-eom-community-fe-1#14]
**버그 설명**
글 수정 시 기존의 이미지 파일 명이 파일 선택 버튼 옆에 뜨면 좋을 것 같습니다

**재현하는 방법**
동작을 재현하는 단계:
1. 이미지가 있는 자신의 게시글로 들어가기
2. 글 수정 버튼 클릭하기

**예상한 동작**
글 수정 시 기존의 이미지 파일 명이 파일 선택 버튼 옆에 뜰 것이라고 생각했음

**스크린샷**
<img width="586" alt="image" src="https://github.com/user-attachments/assets/d9e7b4b4-0534-4972-b03e-49b159306760" />
<img width="589" alt="image" src="https://github.com/user-attachments/assets/33b52b81-68ad-4c2b-b402-30279b74d298" />

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: macOS 14.3
 - Browser: chrome
 - Version 버전 131.0.6778.205(공식 빌드) (arm64)

**Comment by siyeoneom** [comment]
1. 게시글 수정 시에 기존의 이미지 파일을 불러오도록하여 해결
<img width="410" alt="스크린샷 2024-12-31 오후 6 41 03" src="https://github.com/user-attachments/assets/d2ce053e-9896-438a-a063-64ab3727ce65" />

그러나 이미지를 백엔드 서버측에 저장할 때 base64 인코딩된 파일명을 짧게 줄여서 저장하기 때문에 파일명으로는 어떤 이미지인지 판단할 수 없겠다고 생각

2. 기존 이미지 미리보기칸을 추가
<img width="410" alt="스크린샷 2024-12-31 오후 7 19 13" src="https://github.com/user-attachments/assets/c76f2ccc-7df2-4f2c-ac1c-ef1dd1f7d949" />

(아직 QA배포 서버에 업데이트하지않음)
