### ISSUE TITLE
 [MAC-Chrome-1511-게시글 상세] 댓글을 영어로 달았을 때 이슈

### ISSUE THREAD

**Issue by ghkddlscks19** [100-hours-a-week/2-siena-eom-community-fe-1#15]
**버그 설명**
댓글을 영어로 길게 달았을 때 줄바꿈이 되지 않는 버그가 있습니다.

**재현하는 방법**
동작을 재현하는 단계:
1. 아무 게시글 상세 페이지를 들어간다
2. 댓글을 영문으로 줄바꿈이 될 정도로 길게 입력한다
3. 댓글을 작성한다

**예상한 동작**
댓글을 영어로 길게 달았을 때 줄바꿈이 될 것으로 예상했음

**스크린샷**
<img width="655" alt="image" src="https://github.com/user-attachments/assets/dc97e4aa-2b7b-4990-b5f4-5abbddfd625d" />

**데스크톱(다음 정보를 작성해 주세요):**
- OS: macOS 14.3
- Browser: chrome
- Version 버전 131.0.6778.205(공식 빌드) (arm64)

**Comment by siyeoneom** [comment]
css에 overflow-wrap 속성 외 몇 개 추가하여 수정완료했습니다! QA 서버에 업데이트할 예정
